### PR TITLE
add ability to rewrite dependencies with an option

### PR DESCRIPTION
**Pull request by matthewmueller**
This is a non-breaking PR to add ability to supply a function to rewrite the dependency URLs. The normal case works fine for the most part, but sometimes you need a bit more control over what the URL resolves to. This option provides it. 

```js
mako.use(css({
  rewrite: function (file, parent) {
     return '/' + path.relative(parent.dirname, file.relative)
  }
})
``` 

If this works for you, I'll throw up a test.

### CODE REVIEW

**Comment by dominicbarnes** [comment]
That sounds reasonable to me, go ahead and add a test.

**Comment by dominicbarnes** [comment]
Is the use-case you have in mind just setting absolute paths? Would it be easier/more predictable to just add a "base" option that prepends a base url? (ie: `/assets` or `http://cdn.example.com/`)

In what situation would relative paths here not work btw? (I'm open to merging if others find it useful, but personally I feel like it complicates things)

**Comment by matthewmueller** [comment]
So for static builds, you often want routing rules, so like if your folder is named `index`, it moves the files up a directory. Relative assets work fine for that, but my use case was that sometimes I need to reach outside of the pages directory (which is the build's root) for things like shared assets, so I need a way to stick those shared assets in a public folder in the build directory.

**Comment by dominicbarnes** [comment]
I'm going to close this PR, if you still want this in @matthewmueller can you rebase and add the test case?

**Pull request closed without merging**
