### PR TITLE
fix path.relative messing up on some paths

### PR DESCRIPTION
**Pull request by matthewmueller**
Running into a really strange situation with `path.relative` in my testing. Basically `path.relative` is unable to coerce a fullpath and a relative path to a relative path correctly. 

**Here's an example that works**

``` js
var path = require('path')
path.relative('/Users/matt/Projects/mako-css/test/fixtures/assets', 'test/fixtures/assets/texture.png')
// => 'texture.png'
```

**Here's one that doesn't work**

``` js
var path = require('path')
path.relative('/Users/matt/Projects/elmo/test/fixtures/tmp/images-css-r8f/pages/index', 'pages/index/image.png')
// => '../../../../../../pages/index/image.png'
```

Not really sure what's going on here, but I think it's probably a good idea to avoid doing `path.relative(absolutePath, relativePath)`, so this PR changes it to `path.relative(relativePath, relativePath)`

### CODE REVIEW

**Comment by dominicbarnes** [comment]
What's the original CSS? (and what is the folder structure like for your CSS + images?)

If we're going to change something so deep here, I'd like to see a test case that illustrates the problem too.

**Comment by matthewmueller** [comment]
yah, i haven't been able to reproduce it in the tests yet. the crux of the problem seems to be how path.relative resolves paths, so if i figure that out, it should be pretty easy to add a test case.

**Comment by matthewmueller** [comment]
^ okay, the problem happens when the root is not the same as the current working directory. the way path.relative works is it uses `path.resolve(dep)` internally. `path.resolve` uses the CWD to make the relative path absolute. We need to make sure that it uses the `file.base`, not CWD.

**Comment by dominicbarnes** [comment]
Awesome! Glad we were able to get this fix narrowed down and added a test case. Thanks!

**Pull request merged**
